name: custom_lint_avoid_null_check_operator_example
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  custom_lint:
  custom_lint_avoid_null_check_operator:
    path: ..
  lints: ^5.0.0
  test: ^1.24.0
